export const FETCH_PRODUCTS_RECENT = 'FETCH_PRODUCTS_RECENT';
export const FETCH_PRODUCTS_RECENT_SUCCESS = 'FETCH_PRODUCTS_RECENT_SUCCESS';
export const FETCH_PRODUCTS_RECENT_FAILURE = 'FETCH_PRODUCTS_RECENT_FAILURE';

export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_PRODUCTS_LIST_SUCCESS = 'FETCH_PRODUCTS_LIST_SUCCESS';
export const FETCH_PRODUCTS_LIST_FAILURE = 'FETCH_PRODUCTS_LIST_FAILURE';

export const FETCH_PRODUCTS_DETAIL = 'FETCH_PRODUCTS_DETAIL';
export const FETCH_PRODUCTS_DETAIL_SUCCESS = 'FETCH_PRODUCTS_DETAIL_SUCCESS';
export const FETCH_PRODUCTS_DETAIL_FAILURE = 'FETCH_PRODUCTS_DETAIL_FAILURE';

// export const DELETE_SITE = 'DELETE_SITE';
